name: Plugin Publish
on:
  release:
    types: [created]
jobs:
  Publish:
    name: Publish artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build Go Plugin
        run: go build -buildmode=plugin -o build/hello.so plugins/hello/main.go

      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: path/to/artifact
